# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_files/YTui_formatWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_formatWindow(object):
    def setupUi(self, formatWindow):
        formatWindow.setObjectName("formatWindow")
        formatWindow.resize(243, 88)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(formatWindow.sizePolicy().hasHeightForWidth())
        formatWindow.setSizePolicy(sizePolicy)
        formatWindow.setMaximumSize(QtCore.QSize(243, 93))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("ui_files\\../icon.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        formatWindow.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(formatWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.mp3Button = QtWidgets.QRadioButton(self.centralwidget)
        self.mp3Button.setGeometry(QtCore.QRect(30, 20, 82, 17))
        self.mp3Button.setObjectName("mp3Button")
        self.mp4Button = QtWidgets.QRadioButton(self.centralwidget)
        self.mp4Button.setGeometry(QtCore.QRect(100, 20, 41, 17))
        self.mp4Button.setAcceptDrops(False)
        self.mp4Button.setChecked(True)
        self.mp4Button.setObjectName("mp4Button")
        self.webmButton = QtWidgets.QRadioButton(self.centralwidget)
        self.webmButton.setGeometry(QtCore.QRect(170, 20, 82, 17))
        self.webmButton.setObjectName("webmButton")
        formatWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(formatWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 243, 21))
        self.menubar.setObjectName("menubar")
        formatWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(formatWindow)
        self.statusbar.setObjectName("statusbar")
        formatWindow.setStatusBar(self.statusbar)

        self.retranslateUi(formatWindow)
        QtCore.QMetaObject.connectSlotsByName(formatWindow)

    def retranslateUi(self, formatWindow):
        _translate = QtCore.QCoreApplication.translate
        formatWindow.setWindowTitle(_translate("formatWindow", "Change format"))
        self.mp3Button.setText(_translate("formatWindow", "MP3"))
        self.mp4Button.setText(_translate("formatWindow", "MP4"))
        self.webmButton.setText(_translate("formatWindow", "WEBM"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    formatWindow = QtWidgets.QMainWindow()
    ui = Ui_formatWindow()
    ui.setupUi(formatWindow)
    formatWindow.show()
    sys.exit(app.exec_())
