# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_files/video_or_playlist_window.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_playlist_or_video_window(object):
    def setupUi(self, playlist_or_video_window):
        playlist_or_video_window.setObjectName("playlist_or_video_window")
        playlist_or_video_window.resize(312, 167)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("ui_files\\../icon.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        playlist_or_video_window.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(playlist_or_video_window)
        self.centralwidget.setObjectName("centralwidget")
        self.playlist_button = QtWidgets.QRadioButton(self.centralwidget)
        self.playlist_button.setGeometry(QtCore.QRect(60, 60, 51, 17))
        self.playlist_button.setObjectName("playlist_button")
        self.individual_video_button = QtWidgets.QRadioButton(self.centralwidget)
        self.individual_video_button.setGeometry(QtCore.QRect(200, 60, 51, 17))
        self.individual_video_button.setChecked(True)
        self.individual_video_button.setObjectName("individual_video_button")
        self.ok_button = QtWidgets.QPushButton(self.centralwidget)
        self.ok_button.setGeometry(QtCore.QRect(120, 100, 75, 23))
        self.ok_button.setObjectName("ok_button")
        playlist_or_video_window.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(playlist_or_video_window)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 312, 21))
        self.menubar.setObjectName("menubar")
        playlist_or_video_window.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(playlist_or_video_window)
        self.statusbar.setObjectName("statusbar")
        playlist_or_video_window.setStatusBar(self.statusbar)

        self.retranslateUi(playlist_or_video_window)
        QtCore.QMetaObject.connectSlotsByName(playlist_or_video_window)

    def retranslateUi(self, playlist_or_video_window):
        _translate = QtCore.QCoreApplication.translate
        playlist_or_video_window.setWindowTitle(_translate("playlist_or_video_window", "Choose"))
        self.playlist_button.setText(_translate("playlist_or_video_window", "Playlist"))
        self.individual_video_button.setText(_translate("playlist_or_video_window", "Video"))
        self.ok_button.setText(_translate("playlist_or_video_window", "OK"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    playlist_or_video_window = QtWidgets.QMainWindow()
    ui = Ui_playlist_or_video_window()
    ui.setupUi(playlist_or_video_window)
    playlist_or_video_window.show()
    sys.exit(app.exec_())
